
env:
   global:
     - CONAN_REFERENCE: "llvm/6.0.0"
     - CONAN_USERNAME: "arsen-studio"
     - CONAN_CHANNEL: "testing"
     - CONAN_STABLE_BRANCH_PATTERN: "release/*"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/arsen-studio/arsen-deps"
     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1

     - CONAN_BUILD_TYPES: "Release"

osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *osx
        osx_image: xcode9.4
        env: CONAN_APPLE_CLANG_VERSIONS=9.1
      - <<: *osx
        osx_image: xcode10.3
        env: CONAN_APPLE_CLANG_VERSIONS=10.0
      - <<: *osx
        osx_image: xcode11.2
        env: CONAN_APPLE_CLANG_VERSIONS=11.0

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
